const lessonData = {};

lessonData["01_LevYashin.mp3"] = [{
    text: "Lev Yashin was a famous football player from the Soviet Union. He was born in 1929. People called him the 'Black Spider' because he wore all-black clothes and was an amazing goalkeeper. Many fans think he is the best goalkeeper in football history. He played his whole career for one club, Dynamo Moscow. Yashin also played in four World Cups for his country. He won a very special award called the Ballon d'Or in 1963. He is still the only goalkeeper to win this big prize. Yashin was famous for stopping penalty kicks and for shouting loudly to organize his defenders. He changed how goalkeepers play the game. He died in 1990, but football fans all over the world still remember him today.",
    dict: { "famous": "ünlü", "Soviet Union": "Sovyetler Birliği", "Spider": "Örümcek", "all-black": "tamamen siyah", "clothes": "kıyafetler", "amazing": "şaşırtıcı", "goalkeeper": "kaleci", "history": "tarih", "career": "kariyer", "award": "ödül", "stopping": "durdurma", "penalty kicks": "penaltı vuruşları", "shouting": "bağırma", "loudly": "yüksek sesle", "organize": "organize etmek", "defenders": "savunma oyuncuları" },
    questions: [ {q:"Was Lev Yashin from the Soviet Union?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people call him the 'Black Spider'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he wear all-black clothes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for many different clubs?", a_en:"No", a_tr:"Hayır"}, {q:"Did he win the Ballon d'Or in 1963?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he the only goalkeeper to win the Ballon d'Or?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he change how goalkeepers play?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_GordonBanks.mp3"] = [{
    text: "Gordon Banks was a great English football player. He was born in 1937 in England. He played as a goalkeeper and is famous for being one of the best in the world. Banks played for Leicester City and Stoke City during his career. His most famous moment was in the 1966 World Cup. He helped the England national team win the tournament. This is still England's only World Cup win. Four years later, in the 1970 World Cup, he made a famous save against Pelé. People call it the 'save of the century.' Sadly, he lost the sight in his right eye after a car accident in 1972. This ended his top-level career. Banks was a fantastic player and a true gentleman of the sport.",
    dict: { "great": "harika", "famous": "ünlü", "world": "dünya", "during": "sırasında", "moment": "an", "helped": "yardım etti", "win": "kazanmak", "tournament": "turnuva", "save": "kurtarış", "against": "karşı", "century": "yüzyıl", "sight": "görme yetisi", "right eye": "sağ göz", "accident": "kaza", "top-level": "üst düzey", "fantastic": "fantastik", "gentleman": "beyefendi" },
    questions: [ {q:"Was Gordon Banks an English player?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help England win the World Cup in 1966?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he make a famous save against Pelé?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lose the sight in his left eye?", a_en:"No", a_tr:"Hayır"}, {q:"Did his career end after a car accident?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he known as a true gentleman of the sport?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a midfielder?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["03_DinoZoff.mp3"] = [{
    text: "Dino Zoff is a famous Italian football player. He was born in 1942. He was a fantastic goalkeeper and a great leader on the pitch. Zoff played for big Italian clubs, but he is most famous for his time at Juventus. He won many league titles with them. The best moment of his career happened in 1982. He was the captain of the Italy national team when they won the World Cup. He was 40 years old at the time! This made him the oldest player ever to win the World Cup. Zoff was known for his calm personality and his excellent positioning. After he stopped playing, he became a successful football manager. He is a true legend in Italy and around the world.",
    dict: { "Italian": "İtalyan", "pitch": "saha", "famous": "ünlü", "time": "zaman/dönem", "league titles": "lig şampiyonlukları", "happened": "oldu", "captain": "kaptan", "oldest": "en yaşlı", "ever": "hiç/şimdiye kadar", "known": "bilinen", "calm": "sakin", "personality": "kişilik", "excellent": "mükemmel", "positioning": "pozisyon alma", "manager": "menajer", "around": "etrafında" },
    questions: [ {q:"Is Dino Zoff a famous Italian player?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a fantastic goalkeeper?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Juventus?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the World Cup in 1982?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he 20 years old when he won the World Cup?", a_en:"No", a_tr:"Hayır"}, {q:"Is he the oldest player to win the World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a football manager?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_FranzBeckenbauer.mp3"] = [{
    text: "Franz Beckenbauer was a legendary football player from Germany. He was born in 1945. Fans called him 'Der Kaiser,' which means 'The Emperor,' because he played like a smart leader. He played for Bayern Munich for many years and won many trophies. Beckenbauer was a defender, but he liked to run forward with the ball and start attacks. He invented a new position called the 'sweeper.' He won the World Cup with West Germany in 1974 as the team captain. Then, in 1990, he won the World Cup again as the manager of the German team. He is one of only three people to win the World Cup as both a player and a manager. He is a hero in German football history.",
    dict: { "legendary": "efsanevi", "means": "anlamına gelir", "Emperor": "İmparator", "smart": "akıllı", "leader": "lider", "trophies": "kupalar", "defender": "defans oyuncusu", "forward": "ileriye", "start": "başlatmak", "attacks": "hücumlar", "invented": "icat etti", "new": "yeni", "position": "pozisyon", "sweeper": "libero", "again": "tekrar", "manager": "menajer", "history": "tarih" },
    questions: [ {q:"Was Franz Beckenbauer from Germany?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans call him 'The Emperor'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Bayern Munich?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he invent the 'sweeper' position?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the World Cup as both a player and manager?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the World Cup as manager in 1950?", a_en:"No", a_tr:"Hayır"}, {q:"Is he a hero in German football history?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_BobbyMoore.mp3"] = [{
    text: "Bobby Moore was a famous English football player. He was born in 1941. He played as a defender and was known for being very smart on the pitch. He could read the game perfectly and stop attackers before they scored. Moore played most of his career for West Ham United in London. He is most famous for being the captain of the England national team. In 1966, he led England to win the World Cup at Wembley Stadium. Even the great Pelé said Bobby Moore was the fairest and best defender he ever played against. Moore was a calm leader and always showed respect to other players. Sadly, he died in 1993, but there is a famous statue of him outside Wembley Stadium today.",
    dict: { "defender": "defans oyuncusu", "smart": "akıllı", "read": "okumak", "perfectly": "mükemmelce", "attackers": "hücumcular", "before": "önce", "career": "kariyer", "led": "yönetti", "Stadium": "Stadyum", "fairest": "en adil", "against": "karşı", "calm": "sakin", "respect": "saygı", "statue": "heykel", "outside": "dışında" },
    questions: [ {q:"Was Bobby Moore an English defender?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play most of his career for West Ham United?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lead England to win the World Cup in 1966?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Pelé say Moore was a bad defender?", a_en:"No", a_tr:"Hayır"}, {q:"Was he a calm leader?", a_en:"Yes", a_tr:"Evet"}, {q:"Is there a statue of him outside Wembley Stadium?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play rough and show no respect?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["06_CarlosAlberto.mp3"] = [{
    text: "Carlos Alberto was a brilliant Brazilian football player. He was born in 1944. He played as a right-back, which is a defender who also helps the team attack. He played for famous clubs in Brazil like Santos, where he played with Pelé. Carlos Alberto was a strong leader and the captain of the Brazil national team. His most famous moment was in the 1970 World Cup final against Italy. He scored one of the most beautiful goals in football history. The whole team passed the ball, and Carlos Alberto ran very fast to kick it into the net. Brazil won the World Cup, and he proudly lifted the trophy. He showed the world how exciting a modern defender could be. He passed away in 2016.",
    dict: { "brilliant": "parlak/harika", "right-back": "sağ bek", "helps": "yardım eder", "attack": "hücum", "strong": "güçlü", "final": "final", "beautiful": "güzel", "history": "tarih", "passed": "paslaştı", "kick": "vurmak", "net": "ağ/file", "proudly": "gururla", "lifted": "kaldırdı", "trophy": "kupa", "exciting": "heyecan verici", "modern": "modern", "passed away": "vefat etti" },
    questions: [ {q:"Was Carlos Alberto from Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play as a right-back?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Santos with Pelé?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score a beautiful goal in the 1970 World Cup final?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Italy win the World Cup in 1970?", a_en:"No", a_tr:"Hayır"}, {q:"Did he proudly lift the trophy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he show how boring a defender could be?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["07_DanielPassarella.mp3"] = [{
    text: "Daniel Passarella is a famous football player from Argentina. He was born in 1953. He played as a central defender. Even though he was not very tall for a defender, he was fantastic at jumping and heading the ball. Passarella was a tough player and a very strong leader. He played for River Plate in Argentina and later played in Italy. He is most famous for being the captain of the Argentina national team in 1978. He led his team to win their very first World Cup in front of their home fans. Passarella was also special because he scored a lot of goals. He scored free-kicks and penalty kicks. He is one of the best scoring defenders in the history of football.",
    dict: { "central": "merkez", "Even though": "rağmen", "tall": "uzun", "jumping": "zıplama", "heading": "kafa vurma", "tough": "sert/zorlu", "later": "daha sonra", "very first": "ilk defa/en ilk", "in front of": "önünde", "home": "ev/kendi sahası", "because": "çünkü", "free-kicks": "serbest vuruşlar", "penalty kicks": "penaltı vuruşları", "best": "en iyi", "scoring": "gol atan" },
    questions: [ {q:"Is Daniel Passarella from Argentina?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a central defender?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he very tall?", a_en:"No", a_tr:"Hayır"}, {q:"Was he fantastic at jumping and heading?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lead Argentina to win the 1978 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score many goals?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score free-kicks and penalty kicks?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_GiacintoFacchetti.mp3"] = [{
    text: "Giacinto Facchetti was a legendary football player from Italy. He was born in 1942. He played as a left-back defender for Inter Milan. He spent his entire football career at this one club. Facchetti was very tall, fast, and strong. Before him, defenders usually stayed back to protect the goal. But Facchetti loved to run forward and help his team score goals. He was one of the first attacking full-backs in the world. He won many Italian league titles and European cups with Inter Milan. He was also the captain of the Italy national team and helped them win the European Championship in 1968. He was known for being a very fair and honest player. He died in 2006, and Inter Milan retired his number 3 shirt.",
    dict: { "left-back": "sol bek", "spent": "geçirdi", "entire": "bütün/tüm", "tall": "uzun", "Before": "öncesinde", "usually": "genellikle", "stayed back": "geride kalırdı", "protect": "korumak", "attacking": "hücum eden", "full-backs": "bekler", "league titles": "lig şampiyonlukları", "captain": "kaptan", "win": "kazanmak", "fair": "adil", "honest": "dürüst", "retired": "emekli etti (numarayı)", "shirt": "forma" },
    questions: [ {q:"Did Giacinto Facchetti play for Inter Milan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for many different clubs?", a_en:"No", a_tr:"Hayır"}, {q:"Was he one of the first attacking full-backs?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he love to run forward and help score goals?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the European Championship in 1968?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very unfair and dishonest player?", a_en:"No", a_tr:"Hayır"}, {q:"Did Inter Milan retire his number 3 shirt?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_GaetanoScirea.mp3"] = [{
    text: "Gaetano Scirea was a wonderful Italian football player. He was born in 1953. He played as a defender, mostly in a position called a 'sweeper.' Scirea was famous for being very calm, polite, and elegant on the football pitch. Unlike many other defenders of his time, he played rough at no time and showed no anger. In his whole career, he received zero red cards! He played for Juventus for many years and won every major trophy with them. Scirea was also a key player for the Italy national team. He helped Italy win the World Cup in 1982. He was a quiet leader who organized the team beautifully. Tragically, he died in a car accident in 1989 when he was only 36 years old.",
    dict: { "wonderful": "harika", "mostly": "çoğunlukla", "sweeper": "libero", "calm": "sakin", "polite": "kibar", "elegant": "zarif/şık", "Unlike": "Aksine/Farklı olarak", "rough": "sert", "at no time": "hiçbir zaman", "anger": "öfke", "received": "aldı", "zero": "sıfır", "every": "her/bütün", "major": "büyük/ana", "trophy": "kupa", "key": "kilit/önemli", "quiet": "sessiz", "organized": "organize etti", "Tragically": "trajik bir şekilde", "accident": "kaza" },
    questions: [ {q:"Was Gaetano Scirea an Italian player?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play as a sweeper?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play rough at no time?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he receive many red cards?", a_en:"No", a_tr:"Hayır"}, {q:"Did he win every major trophy with Juventus?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Italy win the World Cup in 1982?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he live until he was eighty years old?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["10_RuudKrol.mp3"] = [{
    text: "Ruud Krol is a famous football player from the Netherlands. He was born in 1949. He played as a defender for the great Ajax team in the 1970s. Krol was an important part of a style called 'Total Football.' In this style, players could easily change positions during the game. Krol started as a left-back but later played as a central sweeper. He was very comfortable with the ball and could pass it beautifully with both feet. He won three European Cups in a row with Ajax. He also played for the Dutch national team and reached two World Cup finals in 1974 and 1978. Krol was a strong, stylish player who showed that defenders could be just as skilled as attackers.",
    dict: { "Netherlands": "Hollanda", "part": "parça/bölüm", "style": "stil/tarz", "Total": "Total/Bütüncül", "easily": "kolayca", "change": "değiştirmek", "positions": "pozisyonlar", "started": "başladı", "comfortable": "rahat/emin", "both feet": "her iki ayak", "in a row": "üst üste", "reached": "ulaştı/çıktı", "finals": "finaller", "stylish": "şık/tarz sahibi", "skilled": "yetenekli", "attackers": "hücumcular" },
    questions: [ {q:"Is Ruud Krol from the Netherlands?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Ajax?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he part of the 'Total Football' style?", a_en:"Yes", a_tr:"Evet"}, {q:"Could players in this style change positions easily?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he pass the ball with both feet?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win zero European Cups?", a_en:"No", a_tr:"Hayır"}, {q:"Did he reach two World Cup finals?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["11_EliasFigueroa.mp3"] = [{
    text: "Elias Figueroa was a great football player from Chile. He was born in 1946. He played as a central defender. Many people think he is the best player in the history of Chile. Figueroa played for clubs in Chile, Uruguay, and Brazil. He was very successful in Brazil with a team called Internacional. He was a very elegant and smart defender. He could read the game well and was very strong in the air. He was the captain of the Chile national team and played in three World Cups. He won the 'South American Footballer of the Year' award three times in a row. This is very rare for a defender. He is a true legend in South America.",
    dict: { "Chile": "Şili", "best": "en iyi", "history": "tarih", "successful": "başarılı", "elegant": "zarif", "read": "okumak", "strong": "güçlü", "air": "hava", "three": "üç", "award": "ödül", "times": "kez/defa", "rare": "nadir", "true": "gerçek", "legend": "efsane", "South America": "Güney Amerika" },
    questions: [ {q:"Was Elias Figueroa from Chile?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a striker?", a_en:"No", a_tr:"Hayır"}, {q:"Did he play for Internacional in Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he strong in the air?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the South American Footballer of the Year award three times?", a_en:"Yes", a_tr:"Evet"}, {q:"Is winning this award rare for a defender?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he a true legend in South America?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_JohnCharles.mp3"] = [{
    text: "John Charles was a famous football player from Wales. He was born in 1931. He was very special because he could play as a central defender or a main striker. He was fantastic at both positions! He started his career at Leeds United in England and scored many goals. In 1957, he moved to Italy to play for Juventus. The Italian fans loved him. They called him 'Il Gigante Buono,' which means 'The Gentle Giant.' He was very tall and strong, but he caused harm to nobody. In his whole career, he received zero yellow or red cards. He played for Wales in the 1958 World Cup. He died in 2004, but fans still remember his great sportsmanship.",
    dict: { "Wales": "Galler", "main": "ana/temel", "striker": "forvet", "both": "her ikisi", "positions": "pozisyonlar", "Gentle": "Nazik/Kibar", "Giant": "Dev", "tall": "uzun", "caused": "sebep oldu", "harm": "zarar", "nobody": "hiç kimse", "received": "aldı", "zero": "sıfır", "yellow": "sarı", "red": "kırmızı", "cards": "kartlar", "remember": "hatırlar", "sportsmanship": "sportmenlik" },
    questions: [ {q:"Was John Charles from Wales?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he play as both a defender and a striker?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he move to Juventus in Italy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people call him 'The Angry Giant'?", a_en:"No", a_tr:"Hayır"}, {q:"Did he cause harm to nobody?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he receive zero yellow or red cards in his career?", a_en:"Yes", a_tr:"Evet"}, {q:"Do fans still remember his great sportsmanship?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_DiegoMaradona.mp3"] = [{
    text: "Diego Maradona was a football genius from Argentina. He was born in 1960. He was short but very strong, and he had amazing control of the ball. He played for Barcelona in Spain and Napoli in Italy. In Naples, the fans treated him like a king because he helped them win the Italian league. His most famous tournament was the 1986 World Cup in Mexico. He was the captain of Argentina and led them to become world champions. In one game against England, he scored two very famous goals. One was with his hand, called the 'Hand of God,' and the other was a beautiful solo run. Maradona had a difficult life off the pitch, but he is one of the greatest players ever. He died in 2020.",
    dict: { "genius": "dahi", "short": "kısa", "control": "kontrol", "treated": "davrandılar", "king": "kral", "helped": "yardım etti", "league": "lig", "tournament": "turnuva", "captain": "kaptan", "world champions": "dünya şampiyonları", "game": "oyun/maç", "Hand": "El", "God": "Tanrı", "other": "diğeri", "solo": "tek başına", "run": "koşu", "difficult": "zor", "off": "dışında", "greatest": "en büyük" },
    questions: [ {q:"Was Diego Maradona from Argentina?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very tall player?", a_en:"No", a_tr:"Hayır"}, {q:"Did he help Napoli win the Italian league?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lead Argentina to win the 1986 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score a goal with his hand called the 'Hand of God'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score a goal after a beautiful solo run?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he one of the greatest players ever?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_MichelPlatini.mp3"] = [{
    text: "Michel Platini is a famous football player from France. He was born in 1955. He played as an attacking midfielder. He was a fantastic passer and scored many beautiful free-kicks. Platini played for Nancy and Saint-Étienne in France, but he became a global star at Juventus in Italy. He won the Ballon d'Or award three times in a row in the 1980s. He was the captain of the France national team. In 1984, he led France to win the European Championship and scored nine goals in the tournament! This is still a record today. After he stopped playing, he became a football manager and a very important leader in European football. He is a hero in French sports history.",
    dict: { "attacking": "hücum eden", "midfielder": "orta saha", "fantastic": "harika", "passer": "pasör", "free-kicks": "serbest vuruşlar", "global": "küresel", "star": "yıldız", "award": "ödül", "in a row": "üst üste", "national team": "milli takım", "nine": "dokuz", "record": "rekor", "After": "sonra", "manager": "menajer", "important": "önemli", "leader": "lider" },
    questions: [ {q:"Is Michel Platini from France?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play as a goalkeeper?", a_en:"No", a_tr:"Hayır"}, {q:"Did he score many beautiful free-kicks?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or award three times in a row?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lead France to win the European Championship in 1984?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score nine goals in the 1984 tournament?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a football manager?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_BobbyCharlton.mp3"] = [{
    text: "Bobby Charlton was a legendary English football player. He was born in 1937. He played as an attacking midfielder and was famous for his very hard shots from a long distance. He spent almost his whole career at Manchester United. In 1958, he survived a terrible airplane crash in Munich that killed many of his teammates. Charlton helped rebuild the team. Ten years later, he helped Manchester United win the European Cup. He was also a key player for the England national team. He won the World Cup with England in 1966 and won the Ballon d'Or in the same year. He was a true gentleman on and off the pitch. He passed away in 2023, leaving a great legacy.",
    dict: { "legendary": "efsanevi", "hard": "sert", "shots": "şutlar", "long distance": "uzak mesafe", "survived": "hayatta kaldı", "terrible": "korkunç", "airplane": "uçak", "crash": "kaza", "killed": "öldürdü", "teammates": "takım arkadaşları", "rebuild": "yeniden inşa etmek", "key": "kilit/önemli", "same": "aynı", "gentleman": "beyefendi", "off": "dışında", "legacy": "miras" },
    questions: [ {q:"Was Bobby Charlton a legendary English player?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for hard shots from long distance?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Manchester United?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he survive a terrible airplane crash in 1958?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he refuse to rebuild the team?", a_en:"No", a_tr:"Hayır"}, {q:"Did he win the World Cup with England in 1966?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a true gentleman?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_Zico.mp3"] = [{
    text: "Zico is a famous football player from Brazil. His real name is Arthur Antunes Coimbra. He was born in 1953. People often called him the 'White Pelé' because he was incredibly skilled. He played as an attacking midfielder and wore the famous number 10 shirt. He was a master at passing, dribbling, and taking free-kicks. Zico played most of his career for Flamengo in Brazil, where he scored hundreds of goals and won many trophies. He also played in Italy and Japan. Zico played for the Brazil national team in three World Cups. Even though he won zero World Cups, many fans think his 1982 team was one of the best ever. He is a true icon of beautiful football.",
    dict: { "real": "gerçek", "White": "Beyaz", "because": "çünkü", "incredibly": "inanılmaz derecede", "skilled": "yetenekli", "number 10": "numara 10", "shirt": "forma", "master": "usta", "hundreds": "yüzlerce", "trophies": "kupalar", "Japan": "Japonya", "Even though": "rağmen", "zero": "sıfır", "icon": "ikon/sembol" },
    questions: [ {q:"Is Zico a famous player from Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people call him the 'White Pelé'?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a goalkeeper?", a_en:"No", a_tr:"Hayır"}, {q:"Was he a master at free-kicks?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score hundreds of goals for Flamengo?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win many World Cups?", a_en:"No", a_tr:"Hayır"}, {q:"Did he win zero World Cups?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_GeorgeBest.mp3"] = [{
    text: "George Best was a wonderful football player from Northern Ireland. He was born in 1946. He played as a winger, mostly for Manchester United. Best was famous for his amazing dribbling skills. He could easily run past many defenders with the ball. In 1968, he helped Manchester United win the European Cup and he won the Ballon d'Or award. He was one of the first celebrity football players. He looked like a pop star and was very famous off the pitch too. Unfortunately, he had problems with alcohol, and his top-level career ended early. Even though his career was short, people who saw him play will forget his incredible talent at no point. He died in 2005.",
    dict: { "wonderful": "harika", "Northern Ireland": "Kuzey İrlanda", "winger": "kanat oyuncusu", "mostly": "çoğunlukla", "easily": "kolayca", "past": "geçmek", "celebrity": "ünlü", "pop star": "pop yıldızı", "off": "dışında", "Unfortunately": "ne yazık ki", "problems": "sorunlar", "alcohol": "alkol", "top-level": "üst düzey", "ended": "bitti", "short": "kısa", "at no point": "hiçbir zaman/noktada" },
    questions: [ {q:"Was George Best from Northern Ireland?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play as a winger?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for amazing dribbling skills?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Manchester United win the European Cup in 1968?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he look like a pop star?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have a very long top-level career?", a_en:"No", a_tr:"Hayır"}, {q:"Will people forget his talent at some point?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["18_Rivellino.mp3"] = [{
    text: "Rivellino is a famous football player from Brazil. He was born in 1946. He played as an attacking midfielder. He is very famous for his powerful left foot and his fantastic free-kicks. He also invented a very popular football trick called the 'flip flap' or 'elastico,' where a player moves the ball quickly from one side to the other. Rivellino played for Corinthians and Fluminense in Brazil. He was a very important player for the Brazil national team. He played in the 1970 World Cup and helped Brazil win the tournament with a legendary team. His big mustache and his powerful shots made him a favorite player for many fans around the world.",
    dict: { "powerful": "güçlü", "left foot": "sol ayak", "fantastic": "harika", "invented": "icat etti/buldu", "popular": "popüler", "trick": "numara", "flip flap": "çalım (flip flap)", "moves": "hareket ettirir", "quickly": "hızlıca", "side": "taraf", "other": "diğer", "legendary": "efsanevi", "mustache": "bıyık", "shots": "şutlar", "favorite": "favori" },
    questions: [ {q:"Is Rivellino from Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for his powerful left foot?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he invent the 'flip flap' trick?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Brazil win the 1970 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have a big mustache?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a goalkeeper?", a_en:"No", a_tr:"Hayır"}, {q:"Did he play in the 1970 World Cup with a legendary team?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_Socrates.mp3"] = [{
    text: "Sócrates was a very unique football player from Brazil. He was born in 1954. He was very tall and played as an attacking midfielder. He was famous for his beautiful passes and his clever backheel kicks. He played mostly for Corinthians in Brazil. Sócrates was no mere football player; he was also a medical doctor! He was a very smart man who cared a lot about politics and democracy in his country. He was the captain of the famous Brazil national team in the 1982 World Cup. They played beautiful, attacking football, but won no trophy in the end. Sócrates was a leader on the pitch and a thinker off the pitch. He sadly died in 2011.",
    dict: { "unique": "eşsiz", "tall": "uzun", "beautiful": "güzel", "clever": "zeki", "backheel": "topuk", "kicks": "vuruşlar/şutlar", "no mere": "sadece değil", "medical doctor": "tıp doktoru", "smart": "akıllı", "cared": "önemsedi", "politics": "politika", "democracy": "demokrasi", "won no trophy": "kupa kazanamadı", "leader": "lider", "thinker": "düşünür", "sadly": "ne yazık ki" },
    questions: [ {q:"Was Sócrates a tall attacking midfielder?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for clever backheel kicks?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he also a medical doctor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he care nothing about politics?", a_en:"No", a_tr:"Hayır"}, {q:"Was he the captain of Brazil in the 1982 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Brazil win the World Cup trophy in 1982?", a_en:"No", a_tr:"Hayır"}, {q:"Was he a thinker off the pitch?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_JohanNeeskens.mp3"] = [{
    text: "Johan Neeskens was a great football player from the Netherlands. He was born in 1951. He played as a midfielder. He was an essential part of the famous 'Total Football' teams of the 1970s. Neeskens was a very energetic and hardworking player. He ran all over the pitch, won the ball back, and scored goals too. He played with Johan Cruyff at Ajax in the Netherlands and Barcelona in Spain. He won three European Cups with Ajax. Neeskens also played in two World Cup finals for the Dutch national team in 1974 and 1978. In the 1974 final, he scored a famous penalty kick very early in the game. He was a strong and tireless player.",
    dict: { "essential": "temel/gerekli", "hardworking": "çalışkan", "all over": "her yerinde", "too": "ayrıca/de-da", "row": "sıra", "finals": "finaller", "early": "erken", "tireless": "yorulmak bilmez" },
    questions: [ {q:"Was Johan Neeskens from the Netherlands?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he part of the 'Total Football' teams?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very lazy player?", a_en:"No", a_tr:"Hayır"}, {q:"Did he play with Johan Cruyff?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win three European Cups with Ajax?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he reach two World Cup finals?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score a penalty in the 1974 final?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_Didi.mp3"] = [{
    text: "Didi was a famous football player from Brazil. He was born in 1928. He played as a midfielder and was known for his elegant style. He was a very smart player who controlled the game with his passing. Didi is famous for inventing a special way to kick the ball called the 'falling leaf.' The ball goes up high and then drops suddenly into the goal. He played for Brazilian clubs like Botafogo and Fluminense, and also for Real Madrid in Spain. He was a very important player for the Brazil national team. He helped them win two World Cups in 1958 and 1962. Didi was a true artist on the football pitch. He died in 2001, but fans still remember his beautiful skills.",
    dict: { "known": "bilinen", "elegant": "zarif", "style": "stil", "controlled": "kontrol etti", "passing": "pas verme", "inventing": "icat ederek", "way": "yol/yöntem", "falling": "düşen", "leaf": "yaprak", "goes up": "yukarı çıkar", "drops": "düşer", "suddenly": "aniden", "artist": "sanatçı", "still": "hala", "skills": "beceriler/yetenekler" },
    questions: [ {q:"Was Didi from Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he known for an elegant style?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he invent the 'falling leaf' kick?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the ball drop suddenly with this kick?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Real Madrid?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Brazil win zero World Cups?", a_en:"No", a_tr:"Hayır"}, {q:"Was he a true artist on the pitch?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["22_RaymondKopa.mp3"] = [{
    text: "Raymond Kopa was a great football player from France. He was born in 1931. He played as an attacking midfielder. He was not very tall, but he was very fast and an amazing dribbler. Defenders found it very hard to take the ball from him. Kopa played for Reims in France and then moved to Real Madrid in Spain. At Real Madrid, he played with other famous players and won the European Cup three times. In 1958, he won the Ballon d'Or award. He also played for the France national team in the 1958 World Cup. He helped his country finish in third place. Kopa was one of the first French football stars. He passed away in 2017.",
    dict: { "attacking": "hücum eden", "tall": "uzun", "amazing": "şaşırtıcı", "dribbler": "top süren oyuncu", "found": "buldu", "hard": "zor", "take": "almak", "moved": "taşındı", "three times": "üç kez", "finish": "bitirmek", "third": "üçüncü", "place": "yer/sıra", "stars": "yıldızlar", "passed away": "vefat etti" },
    questions: [ {q:"Was Raymond Kopa from France?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he an attacking midfielder?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very tall player?", a_en:"No", a_tr:"Hayır"}, {q:"Did defenders find it easy to take the ball from him?", a_en:"No", a_tr:"Hayır"}, {q:"Did he win the European Cup three times with Real Madrid?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or in 1958?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help France finish in third place in 1958?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["23_LuisSuarez.mp3"] = [{
    text: "Luis Suárez was a wonderful football player from Spain. He was born in 1935. He played as a midfielder and was famous for his beautiful, long passes. People called him 'The Architect' because he organized the game perfectly. He started his career at Barcelona in Spain and won the Ballon d'Or award in 1960. He is still the only male Spanish player to win this big prize. Later, he moved to Italy to play for Inter Milan. He helped Inter win many Italian leagues and İki European Cups. He was also an important player for the Spain national team. He helped Spain win the European Championship in 1964. He died in 2023.",
    dict: { "Wonderful": "Harika", "long passes": "uzun paslar", "Architect": "Mimar", "organized": "organize etti/düzenledi", "perfectly": "mükemmelce", "male": "erkek", "prize": "ödül", "leagues": "ligler", "Championship": "Şampiyona" },
    questions: [ {q:"Was Luis Suárez from Spain?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a goalkeeper?", a_en:"No", a_tr:"Hayır"}, {q:"Did people call him 'The Architect'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or in 1960?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he the only male Spanish player to win the prize?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he move to Inter Milan in Italy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Spain win the European Championship in 1964?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["24_GianniRivera.mp3"] = [{
    text: "Gianni Rivera is a famous football player from Italy. He was born in 1943. He played as an attacking midfielder. Italian fans called him the 'Golden Boy' because he was incredibly talented from a young age. He played almost his whole career for AC Milan. He was their captain for many years. Rivera was an elegant player who made perfect passes to the strikers. He helped AC Milan win many trophies, including Italian leagues and İki European Cups. In 1969, he won the Ballon d'Or award. He also played for the Italy national team and won the European Championship in 1968. After he stopped playing, he became a politician in Italy.",
    dict: { "Golden": "Altın", "Boy": "Çocuk/Oğlan", "incredibly": "inanılmaz derecede", "talented": "yetenekli", "young age": "genç yaş", "whole": "bütün/tüm", "strikers": "forvetler", "including": "dahil olmak üzere", "politician": "politikacı" },
    questions: [ {q:"Is Gianni Rivera from Italy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans call him the 'Golden Boy'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play almost his whole career for AC Milan?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he their captain?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or in 1969?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for the France national team?", a_en:"No", a_tr:"Hayır"}, {q:"Did he become a politician in Italy?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["25_TeofiloCubillas.mp3"] = [{
    text: "Teófilo Cubillas is a legendary football player from Peru. He was born in 1949. He played as an attacking midfielder. Many people think he is the greatest Peruvian player in history. He was famous for his great technique, fast dribbling, and powerful free-kicks. Cubillas played in three World Cups for Peru. He played amazingly well and scored a total of 10 goals in World Cup tournaments. Very few midfielders have scored this many goals in the World Cup! He played for clubs in Peru, Switzerland, Portugal, and the United States. He was a very fair player and received zero red cards in his career. He is a true hero in his home country.",
    dict: { "legendary": "efsanevi", "greatest": "en büyük", "Peruvian": "Perulu", "history": "tarih", "technique": "teknik", "fast": "hızlı", "dribbling": "top sürme", "well": "iyi", "total": "toplam", "midfielders": "orta saha oyuncuları", "few": "az", "fair": "adil", "received zero": "sıfır aldı", "red cards": "kırmızı kartlar", "hero": "kahraman", "home": "memleket/ev" },
    questions: [ {q:"Was Teófilo Cubillas from Peru?", a_en:"Yes", a_tr:"Evet"}, {q:"Do people think he is the greatest Peruvian player?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for powerful free-kicks?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score a total of 10 goals in World Cup tournaments?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play in five World Cups?", a_en:"No", a_tr:"Hayır"}, {q:"Did he receive zero red cards in his career?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he a hero in his home country?", a_en:"Yes", a_tr:"Evet"} ]
}];lessonData["26_Falcao.mp3"] = [{
    text: "Paulo Roberto Falcão is a famous football player from Brazil. He was born in 1953. He played as a central midfielder. He was a very elegant and intelligent player. He always seemed to know exactly where the ball should go. Falcão started his career at Internacional in Brazil. Then, in 1980, he moved to Italy to play for AS Roma. The fans in Rome loved him so much that they called him the 'Eighth King of Rome.' He helped the team win the Italian league. Falcão also played for the Brazil national team in the 1982 World Cup. Even though Brazil failed to win, they played beautiful football, and Falcão was a key part of that famous team.",
    dict: { "elegant": "zarif", "intelligent": "zeki", "seemed": "göründü", "exactly": "tam olarak", "where": "nereye", "should go": "gitmeli", "started": "başladı", "moved": "taşındı", "Eighth": "Sekizinci", "King": "Kral", "helped": "yardım etti", "win": "kazanmak", "Even though": "rağmen", "failed": "başarısız oldu", "beautiful": "güzel", "key": "kilit", "part": "parça" },
    questions: [ {q:"Is Falcão a famous football player from Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play as a central midfielder?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the fans call him the 'Eighth King of Rome'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help AS Roma win the Italian league?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Brazil win the 1982 World Cup?", a_en:"No", a_tr:"Hayır"}, {q:"Was he a key part of the famous 1982 Brazil team?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play with no intelligence on the pitch?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["27_Pele.mp3"] = [{
    text: "Pelé is one of the most famous football players in history. His real name was Edson Arantes do Nascimento. He was born in Brazil in 1940. He played as a forward and scored hundreds of goals during his career. People called him 'The King' of football. Pelé started playing for the Brazilian club Santos when he was just a teenager. He is most famous for his success with the Brazil national team. He is the only player ever to win three World Cups, in 1958, 1962, and 1970. He was fast, strong, and could shoot perfectly with both feet. He later played in the United States for the New York Cosmos to help make football popular there. He died in 2022.",
    dict: { "history": "tarih", "forward": "forvet", "hundreds": "yüzlerce", "King": "Kral", "just": "sadece", "teenager": "genç", "success": "başarı", "only": "tek", "ever": "hiç/şimdiye kadar", "win": "kazanmak", "strong": "güçlü", "perfectly": "mükemmelce", "both": "her ikisi", "feet": "ayaklar", "popular": "popüler" },
    questions: [ {q:"Is Pelé one of the most famous players in history?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people call him 'The King'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score hundreds of goals?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he the only player ever to win three World Cups?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he shoot with only his right foot?", a_en:"No", a_tr:"Hayır"}, {q:"Did he help make football popular in the United States?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win exactly zero World Cups?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["28_JohanCruyff.mp3"] = [{
    text: "Johan Cruyff was a football genius from the Netherlands. He was born in 1947. He played as an attacking midfielder and forward. He was the star of a famous style called 'Total Football.' Cruyff was incredibly skilled and fast. He even invented a famous dribbling move called the 'Cruyff Turn,' which players still use today. He played for Ajax in the Netherlands and Barcelona in Spain. He won three European Cups with Ajax and won the Ballon d'Or award three times. He led the Dutch national team to the World Cup final in 1974. After playing, he became a brilliant manager and changed how Barcelona plays football. He passed away in 2016.",
    dict: { "genius": "dahi", "attacking": "hücuma dönük", "style": "stil", "Total": "Total/Bütüncül", "skilled": "yetenekli", "invented": "icat etti", "move": "hareket", "still": "hala", "won": "kazandı", "award": "ödül", "times": "kez", "Dutch": "Hollandalı", "final": "final", "brilliant": "parlak/harika", "manager": "menajer", "changed": "değiştirdi", "how": "nasıl" },
    questions: [ {q:"Was Johan Cruyff a football genius from the Netherlands?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the star of 'Total Football'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he invent a famous move called the 'Cruyff Turn'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or award three times?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he lead the Dutch team to the final in 1974?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he change how Barcelona plays football?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a bad manager after he stopped playing?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["29_AlfredoDiStefano.mp3"] = [{
    text: "Alfredo Di Stéfano was a legendary football player. He was born in Argentina in 1926. He is most famous for playing for Real Madrid in Spain. He was an amazing forward, but he could play almost anywhere on the pitch. He helped defend, controlled the midfield, and scored many goals. He was strong, fast, and very smart. Di Stéfano helped Real Madrid win the European Cup five times in a row in the 1950s. He scored a goal in every single final! He played for three different national teams during his career: Argentina, Colombia, and Spain. Many older football fans believe he is the most complete player in the history of the sport. He died in 2014.",
    dict: { "legendary": "efsanevi", "almost": "neredeyse", "anywhere": "herhangi bir yer", "defend": "savunmak", "controlled": "kontrol etti", "midfield": "orta saha", "row": "sıra", "every": "her", "single": "tek", "final": "final", "different": "farklı", "during": "sırasında", "older": "daha yaşlı", "believe": "inanır", "complete": "eksiksiz/tam" },
    questions: [ {q:"Is Alfredo Di Stéfano most famous for playing for Real Madrid?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he play almost anywhere on the pitch?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Real Madrid win the European Cup five times in a row?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score a goal in every single final?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for only one national team?", a_en:"No", a_tr:"Hayır"}, {q:"Do many fans believe he is the most complete player?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die in 2014?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["30_FerencPuskas.mp3"] = [{
    text: "Ferenc Puskás was a fantastic football player from Hungary. He was born in 1927. He played as a forward and was famous for his incredibly powerful left foot. He scored many beautiful goals. Puskás was the captain of the great Hungarian national team in the 1950s. People called them the 'Mighty Magyars.' They suffered almost zero losses and reached the World Cup final in 1954. Later in his career, he moved to Spain and played for Real Madrid. He formed a deadly partnership with Alfredo Di Stéfano. Puskás won three European Cups with Real Madrid. Even though he was a little short and heavy, he was a true goal-scoring machine. He died in 2006.",
    dict: { "fantastic": "harika", "Hungary": "Macaristan", "powerful": "güçlü", "left foot": "sol ayak", "Mighty": "Kudretli", "suffered": "yaşadı/katlandı", "zero": "sıfır", "losses": "yenilgiler", "reached": "ulaştı", "deadly": "ölümcül", "partnership": "ortaklık", "heavy": "ağır", "machine": "makine" },
    questions: [ {q:"Was Ferenc Puskás from Hungary?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for his powerful left foot?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his team suffer almost zero losses in the early 1950s?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he reach the World Cup final in 1954?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Real Madrid later in his career?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very tall and fast player?", a_en:"No", a_tr:"Hayır"}, {q:"Was he a true goal-scoring machine?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["31_Garrincha.mp3"] = [{
    text: "Garrincha was a magical football player from Brazil. He was born in 1933. His real name was Manuel Francisco dos Santos. 'Garrincha' means 'little bird' in Portuguese. He had a difficult childhood, and his legs were not straight. His left leg was shorter than his right leg! But on the football pitch, he was amazing. He played as a right winger. He was famous for his incredible dribbling. Defenders knew nothing about which way he would run. He played most of his career for Botafogo in Brazil. Garrincha helped the Brazil national team win two World Cups in 1958 and 1962. When Pelé was injured in 1962, Garrincha became the star of the tournament. The Brazilian fans loved him very much and called him 'The Joy of the People.' He sadly died in 1983.",
    dict: { "magical": "sihirli", "means": "anlamına gelir", "bird": "kuş", "difficult": "zor", "childhood": "çocukluk", "straight": "düz", "shorter": "daha kısa", "right winger": "sağ kanat", "dribbling": "top sürme", "knew nothing": "hiçbir şey bilmiyorlardı", "injured": "sakatlandı", "Joy": "Neşe", "People": "Halk" },
    questions: [ {q:"Does 'Garrincha' mean 'little bird'?", a_en:"Yes", a_tr:"Evet"}, {q:"Were his legs perfectly straight?", a_en:"No", a_tr:"Hayır"}, {q:"Was he famous for his incredible dribbling?", a_en:"Yes", a_tr:"Evet"}, {q:"Did defenders know exactly which way he would run?", a_en:"No", a_tr:"Hayır"}, {q:"Did he help Brazil win two World Cups?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become the star in 1962 when Pelé was injured?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans call him 'The Joy of the People'?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["32_Eusebio.mp3"] = [{
    text: "Eusébio was a fantastic football player from Portugal. He was born in 1942 in Mozambique, which was a Portuguese colony in Africa. He played as a striker and was famous for his speed and his very powerful right foot. Fans called him the 'Black Panther' because he moved so fast and was so dangerous to defenders. Eusébio played almost his whole career for Benfica in Portugal. He helped them win many league titles and the European Cup in 1962. In 1965, he won the Ballon d'Or award. His most famous tournament was the 1966 World Cup in England. He scored nine goals and helped Portugal finish in third place. He was the top scorer of the tournament. Eusébio was a true gentleman of the game. He passed away in 2014.",
    dict: { "colony": "sömürge", "speed": "hız", "powerful": "güçlü", "Panther": "Panter", "dangerous": "tehlikeli", "league titles": "lig şampiyonlukları", "tournament": "turnuva", "scored": "attı", "third": "üçüncü", "place": "yer/sıra", "scorer": "golcü", "gentleman": "beyefendi", "passed away": "vefat etti" },
    questions: [ {q:"Was Eusébio from Portugal?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he born in Mozambique?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people call him the 'Black Panther'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play almost his whole career for Benfica?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or in 1965?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score nine goals in the 1966 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very rude and angry player?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["33_GerdMuller.mp3"] = [{
    text: "Gerd Müller was a legendary football player from Germany. He was born in 1945. He played as a striker and is one of the best goalscorers in history. People called him 'Der Bomber' because he scored so many goals. He was not very tall or fast, but he was incredibly strong. He always knew exactly where the ball would bounce inside the penalty area. Müller played most of his career for Bayern Munich. He helped them win many German league titles and three European Cups. He also played for the West Germany national team. He won the European Championship in 1972 and the World Cup in 1974. In the 1974 final, he scored the winning goal! He won the Ballon d'Or in 1970. He sadly died in 2021.",
    dict: { "striker": "forvet", "goalscorers": "golcüler", "history": "tarih", "tall": "uzun", "incredibly": "inanılmaz derecede", "strong": "güçlü", "bounce": "sekmek", "penalty area": "ceza sahası", "league": "lig", "won": "kazandı", "winning": "kazandıran" },
    questions: [ {q:"Is Gerd Müller one of the best goalscorers in history?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people call him 'Der Bomber'?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he very tall and fast?", a_en:"No", a_tr:"Hayır"}, {q:"Did he know exactly where the ball would bounce?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win three European Cups with Bayern Munich?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score the winning goal in the 1974 final?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or in 1970?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["34_Jairzinho.mp3"] = [{
    text: "Jairzinho is a famous football player from Brazil. He was born in 1944. He played as a fast and powerful winger. He was very strong and could easily run past defenders. He started his career at Botafogo in Brazil, the same club as his hero, Garrincha. Jairzinho is most famous for his time with the Brazil national team. He played in the 1970 World Cup in Mexico. That Brazilian team is one of the greatest teams ever. Jairzinho did something amazing in that tournament. He scored a goal in every single game! Brazil won the World Cup, and he became a national hero. Fans called him 'The Hurricane' because he was unstoppable on the pitch. He also played in France and helped make football popular there.",
    dict: { "powerful": "güçlü", "winger": "kanat", "easily": "kolayca", "past": "geçmek", "hero": "kahraman", "greatest": "en büyük", "ever": "hiç/şimdiye kadar", "amazing": "şaşırtıcı", "scored": "attı", "Hurricane": "Kasırga", "unstoppable": "durdurulamaz", "pitch": "saha" },
    questions: [ {q:"Was Jairzinho a fast and powerful winger?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he start at the same club as Garrincha?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score a goal in every single game of the 1970 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Brazil win the 1970 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans call him 'The Hurricane'?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he easy for defenders to stop?", a_en:"No", a_tr:"Hayır"}, {q:"Did he help make football popular in France?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["35_PaoloRossi.mp3"] = [{
    text: "Paolo Rossi was a wonderful football player from Italy. He was born in 1956. He played as a striker. He was a small and quick player who was very smart near the goal. He always knew how to find open space to score. He played for Juventus and AC Milan in Italy. Rossi's most famous moment was the 1982 World Cup in Spain. Before the tournament, he had a difficult time and played zero games for two years. But in the World Cup, he was fantastic. He scored a famous hat-trick against a great Brazil team. Then he scored in the semi-final and the final. He helped Italy win the World Cup and became the top scorer. He also won the Ballon d'Or in 1982. He passed away in 2020.",
    dict: { "quick": "hızlı", "smart": "akıllı", "near": "yakın", "find": "bulmak", "open space": "açık alan", "moment": "an", "difficult": "zor", "zero": "sıfır", "fantastic": "harika", "hat-trick": "hat-trick (üç gol)", "final": "final", "top scorer": "gol kralı" },
    questions: [ {q:"Was Paolo Rossi an Italian striker?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very tall and slow player?", a_en:"No", a_tr:"Hayır"}, {q:"Did he play zero games for two years before the 1982 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score a hat-trick against Brazil?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Italy lose the 1982 World Cup?", a_en:"No", a_tr:"Hayır"}, {q:"Did he become the top scorer in 1982?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or in 1982?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["36_KarlHeinzRummenigge.mp3"] = [{
    text: "Karl-Heinz Rummenigge is a famous football player from Germany. He was born in 1955. He played as a forward. He was a very complete player. He was fast, strong, and could dribble very well. He also had a powerful shot. Rummenigge played for Bayern Munich for ten years. He helped them win many trophies, including two European Cups. He was so good that he won the Ballon d'Or award two times in a row, in 1980 and 1981. He also played for the West Germany national team. He helped his country win the European Championship in 1980. He played in two World Cup finals, in 1982 and 1986, but Germany suffered zero wins in those matches. After he stopped playing, he became a very successful leader for Bayern Munich.",
    dict: { "forward": "forvet", "complete": "eksiksiz/tam", "dribble": "top sürmek", "powerful": "güçlü", "shot": "şut", "trophies": "kupalar", "including": "dahil olmak üzere", "in a row": "üst üste", "country": "ülke", "suffered zero wins": "hiç galibiyet alamadı", "successful": "başarılı" },
    questions: [ {q:"Was Rummenigge a very complete player?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Bayern Munich for ten years?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or exactly one time?", a_en:"No", a_tr:"Hayır"}, {q:"Did he win the award two times in a row?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Germany win the European Championship in 1980?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Germany suffer zero wins in the 1982 and 1986 finals?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a leader for Bayern Munich later?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["37_KennyDalglish.mp3"] = [{
    text: "Kenny Dalglish is a legendary football player from Scotland. He was born in 1951. He played as a forward. Fans call him 'King Kenny' because he was so great. He started his career at Celtic in Scotland and won many league titles there. In 1977, he moved to Liverpool in England to replace Kevin Keegan. Dalglish was a very smart player. He scored many goals, but he also made many great passes for his teammates. He helped Liverpool become the best team in Europe. He won three European Cups with Liverpool. He also played for the Scotland national team and is their top scorer. Later, he became a manager for Liverpool and won even more trophies. He is a true hero for Liverpool fans.",
    dict: { "Scotland": "İskoçya", "great": "harika/büyük", "titles": "şampiyonluklar/unvanlar", "moved": "taşındı", "replace": "yerine geçmek", "smart": "akıllı", "made": "yaptı", "passes": "paslar", "teammates": "takım arkadaşları", "manager": "menajer", "hero": "kahraman" },
    questions: [ {q:"Is Kenny Dalglish from Scotland?", a_en:"Yes", a_tr:"Evet"}, {q:"Do fans call him 'King Kenny'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he move to Liverpool to replace Kevin Keegan?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very smart player?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win three European Cups with Liverpool?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he the top scorer for Scotland?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a manager later?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["38_KevinKeegan.mp3"] = [{
    text: "Kevin Keegan is a famous English football player. He was born in 1951. He played as a forward. He was not very tall, but he was incredibly energetic and hardworking. He always ran very fast and gave up on nothing. Keegan started playing for Liverpool in the 1970s. He helped them win three English league titles and their first European Cup in 1977. Then, he did something unusual for English players. He moved to Germany to play for Hamburger SV. In Germany, he was fantastic. He won the Ballon d'Or award two times, in 1978 and 1979. He also played for the England national team and was their captain. Fans loved his exciting style of play and his famous curly hair.",
    dict: { "tall": "uzun", "energetic": "enerjik", "hardworking": "çalışkan", "gave up on nothing": "hiçbir şeyden vazgeçmedi", "titles": "şampiyonluklar", "unusual": "alışılmadık", "fantastic": "harika", "award": "ödül", "captain": "kaptan", "curly": "kıvırcık" },
    questions: [ {q:"Was Kevin Keegan very tall?", a_en:"No", a_tr:"Hayır"}, {q:"Was he incredibly energetic and hardworking?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he give up on nothing?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Liverpool win their first European Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he move to Germany to play for Hamburger SV?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or two times?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans love his exciting style?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["39_MarioKempes.mp3"] = [{
    text: "Mario Kempes is a great football player from Argentina. He was born in 1954. He played as a striker and was famous for his powerful runs and strong left foot. He started his career in Argentina, but he became a star playing for Valencia in Spain. He scored many goals for Valencia and helped them win European trophies. Kempes is a huge hero in Argentina because of the 1978 World Cup. The tournament was played in Argentina. Kempes was the star of the team. He scored six goals in the tournament, including two goals in the final against the Netherlands. He was the top scorer and helped Argentina win their first World Cup. He showed incredible passion and energy on the pitch.",
    dict: { "powerful": "güçlü", "runs": "koşular", "star": "yıldız", "trophies": "kupalar", "hero": "kahraman", "because of": "yüzünden/sebebiyle", "final": "final", "passion": "tutku", "energy": "enerji" },
    questions: [ {q:"Is Mario Kempes from Argentina?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for his powerful runs?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a star at Valencia?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the star of the 1978 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score six goals in that tournament?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help Argentina win their first World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he show zero passion on the pitch?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["40_SandorKocsis.mp3"] = [{
    text: "Sándor Kocsis was a brilliant football player from Hungary. He was born in 1929. He played as a striker and was part of the famous 'Mighty Magyars' team of the 1950s. He played with Ferenc Puskás. Kocsis was incredible at heading the ball. People called him the 'Man with the Golden Head.' He could jump very high and score beautiful goals with his head. He was the top scorer in the 1954 World Cup in Switzerland. He scored 11 goals in just five games! This is an amazing record. Sadly, Hungary lost the final to West Germany. Later in his career, he moved to Spain and played for Barcelona. He helped them win many Spanish league titles. He died tragically in 1979.",
    dict: { "brilliant": "harika/parlak", "striker": "forvet", "Mighty": "Kudretli", "heading": "kafa vuruşu", "Golden": "Altın", "jump": "zıplamak", "high": "yüksek", "record": "rekor", "lost": "kaybetti", "tragically": "trajik bir şekilde" },
    questions: [ {q:"Was Sándor Kocsis from Hungary?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people call him the 'Man with the Golden Head'?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he incredible at heading the ball?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score 11 goals in the 1954 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Hungary win the 1954 final?", a_en:"No", a_tr:"Hayır"}, {q:"Did he play for Barcelona in Spain?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die in 1979?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["41_JustFontaine.mp3"] = [{
    text: "Just Fontaine was a famous football player from France. He was born in 1933. He played as a striker and was an incredible goalscorer. Fontaine is most famous for his amazing performance in the 1958 World Cup in Sweden. In just six games, he scored 13 goals! This is still the record for the most goals scored by one player in a single World Cup tournament. Nobody has ever broken this record. He played mostly for a French club called Reims and helped them reach the European Cup final. Sadly, he had a very bad leg injury and had to stop playing football when he was only 28 years old. Even though his career was short, he is a true football legend. He died in 2023.",
    dict: { "incredible": "inanılmaz", "goalscorer": "golcü", "performance": "performans", "Sweden": "İsveç", "still": "hala", "most": "en çok", "single": "tek/bir", "broken": "kırılmış/geçilmiş", "injury": "sakatlık", "only": "sadece", "legend": "efsane" },
    questions: [ {q:"Was Just Fontaine from France?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score 13 goals in the 1958 World Cup?", a_en:"Yes", a_tr:"Evet"}, {q:"Has anyone broken his 13-goal record?", a_en:"No", a_tr:"Hayır"}, {q:"Did he play mostly for Reims?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he stop playing at the age of 28?", a_en:"Yes", a_tr:"Evet"}, {q:"Was his career very long?", a_en:"No", a_tr:"Hayır"}, {q:"Did he die in 2023?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["42_GiuseppeMeazza.mp3"] = [{
    text: "Giuseppe Meazza was a legendary football player from Italy. He was born in 1910. He played as a forward and was famous for his amazing dribbling and shooting skills. Fans loved watching him because he played beautifully. Meazza played most of his career for Inter Milan. He scored 242 goals for them! He was also the star of the Italy national team. He helped Italy win the World Cup two times in a row, in 1934 and 1938. He was the captain of the 1938 team. He was very famous and was one of the first football players to have personal sponsors. Today, the huge football stadium in Milan is named the Stadio Giuseppe Meazza in his honor. He passed away in 1979.",
    dict: { "legendary": "efsanevi", "forward": "forvet", "shooting": "şut çekme", "beautifully": "güzelce", "goals": "goller", "row": "sıra", "captain": "kaptan", "personal": "kişisel", "sponsors": "sponsorlar", "huge": "kocaman", "honor": "onur", "passed away": "vefat etti" },
    questions: [ {q:"Was Giuseppe Meazza an Italian player?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for his shooting skills?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score 242 goals for Inter Milan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the World Cup exactly zero times?", a_en:"No", a_tr:"Hayır"}, {q:"Did he win the World Cup two times in a row?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the captain in 1938?", a_en:"Yes", a_tr:"Evet"}, {q:"Is a stadium in Milan named after him?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["43_StanleyMatthews.mp3"] = [{
    text: "Stanley Matthews was a very special football player from England. He was born in 1915. He played as an outside right winger. People called him 'The Wizard of the Dribble' because he could keep the ball away from defenders so easily. He played for Stoke City and Blackpool. The most amazing thing about Matthews was his long career. He took very good care of his body and ate healthy food. Because of this, he played professional football until he was 50 years old! In 1956, he won the very first Ballon d'Or award. He also played for the England national team many times. He was a very fair player and received zero yellow or red cards. He died in 2000.",
    dict: { "special": "özel", "outside": "dış", "winger": "kanat", "Wizard": "Büyücü", "keep": "tutmak", "away": "uzakta", "amazing": "şaşırtıcı", "took care": "bakım yaptı/ilgilendi", "body": "vücut", "healthy": "sağlıklı", "until": "kadar", "received zero": "hiç almadı", "fair": "adil" },
    questions: [ {q:"Was Stanley Matthews English?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he called 'The Wizard of the Dribble'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play until he was 50 years old?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the first Ballon d'Or award?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he eat very unhealthy food?", a_en:"No", a_tr:"Hayır"}, {q:"Did he receive many red cards?", a_en:"No", a_tr:"Hayır"}, {q:"Did he receive zero red cards?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["44_TomFinney.mp3"] = [{
    text: "Tom Finney was a wonderful English football player. He was born in 1922. He played as a forward or a winger. He was famous for being very loyal to his hometown club. He played his entire professional career for Preston North End. Fans loved him very much and called him the 'Preston Plumber' because his family had a plumbing business. Finney was a fantastic dribbler and could cross the ball perfectly to his teammates. He played for the England national team in three World Cups. Many players who played against him said he was one of the hardest attackers to stop. After he stopped playing, he did a lot of charity work for his community. He was a true gentleman. He passed away in 2014.",
    dict: { "wonderful": "harika", "loyal": "sadık", "hometown": "memleket", "entire": "bütün/tüm", "Plumber": "Tesisatçı", "plumbing": "tesisat", "cross": "orta yapmak", "hardest": "en zor", "charity work": "hayır işi", "community": "toplum", "gentleman": "beyefendi" },
    questions: [ {q:"Was Tom Finney loyal to his hometown club?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Preston North End?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans call him the 'Preston Plumber'?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he cross the ball perfectly?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play in three World Cups?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he very easy to stop?", a_en:"No", a_tr:"Hayır"}, {q:"Did he do charity work later?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["45_GunnarNordahl.mp3"] = [{
    text: "Gunnar Nordahl was a great football player from Sweden. He was born in 1921. He played as a strong and powerful striker. He started his career in Sweden, but he is most famous for playing in Italy. In 1949, he moved to AC Milan. He was incredibly successful there. Nordahl was the top scorer in the Italian league five times! This is a record that still stands today. He scored 210 goals in the Italian league, which makes him one of the best goalscorers in Italy's history. He also played for the Sweden national team and helped them win a gold medal at the 1948 Olympic Games. He was a very physical player who always found a way to score. He died in 1995.",
    dict: { "Sweden": "İsveç", "strong": "güçlü", "successful": "başarılı", "there": "orada", "top scorer": "gol kralı", "league": "lig", "five times": "beş kez", "stands": "duruyor/geçerli", "gold medal": "altın madalya", "Olympic": "Olimpiyat", "physical": "fiziksel", "found": "buldu" },
    questions: [ {q:"Was Nordahl from Sweden?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a strong and powerful striker?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for AC Milan?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the top scorer in Italy five times?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win a gold medal in 1948?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he always find a way to score?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he a bad goalscorer in Italy's history?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["46_FranciscoGento.mp3"] = [{
    text: "Francisco Gento was a legendary football player from Spain. He was born in 1933. He played as a left winger. He was incredibly fast, and defenders could almost never catch him. Fans called him the 'Cantabrian Gale' because he ran like the wind. Gento played almost his whole career for Real Madrid. He played with other greats like Di Stéfano and Puskás. Gento holds a very special record in football history. He won the European Cup six times! No other player has won it more times than him. He also won the Spanish league 12 times with Real Madrid. He played for the Spain national team in two World Cups. He passed away in 2022.",
    dict: { "left winger": "sol kanat", "fast": "hızlı", "almost": "neredeyse", "catch": "yakalamak", "Gale": "Fırtına", "wind": "rüzgar", "greats": "büyükler", "holds": "elinde tutar", "six times": "altı kez", "No other": "hiçbir diğer", "more": "daha fazla" },
    questions: [ {q:"Is Gento from Spain?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he incredibly fast?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Real Madrid?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the European Cup six times?", a_en:"Yes", a_tr:"Evet"}, {q:"Has any other player won it more times than him?", a_en:"No", a_tr:"Hayır"}, {q:"Did he win the Spanish league 12 times?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die in 2022?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["47_SandroMazzola.mp3"] = [{
    text: "Sandro Mazzola is a famous football player from Italy. He was born in 1942. He played as an attacking midfielder or a forward. His father, Valentino Mazzola, was also a very famous football player who died in a tragic plane crash. Sandro became a legend like his father. He played his entire career for Inter Milan. In the 1960s, he was the star of a great Inter Milan team. He helped them win the European Cup two times in a row, in 1964 and 1965. He also played for the Italy national team. He helped Italy win the European Championship in 1968 and reach the World Cup final in 1970. Mazzola was known for his speed, smart passing, and important goals.",
    dict: { "father": "baba", "tragic": "trajik", "plane crash": "uçak kazası", "legend": "efsane", "entire": "bütün/tüm", "star": "yıldız", "win": "kazanmak", "reach": "ulaşmak", "speed": "hız", "smart": "akıllı", "passing": "pas verme" },
    questions: [ {q:"Is Sandro Mazzola Italian?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his father die in a plane crash?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play his entire career for Inter Milan?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the European Cup two times in a row?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the European Championship in 1968?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he very slow and bad at passing?", a_en:"No", a_tr:"Hayır"}, {q:"Did he score important goals?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["48_UweSeeler.mp3"] = [{
    text: "Uwe Seeler was a beloved football player from Germany. He was born in 1936. He played as a striker. He was not very tall, but he was incredibly strong and fantastic at heading the ball. Seeler was famous for scoring difficult goals, even bicycle kicks! He played his entire club career for Hamburger SV in Germany. He was extremely loyal to his club and refused offers from richer teams in Italy and Spain. He was also the captain of the West Germany national team. He played in four World Cups and reached the final in 1966. Even though he won zero World Cups, he is a massive hero in Germany because of his sportsmanship and warm personality. He passed away in 2022.",
    dict: { "beloved": "sevilen", "strong": "güçlü", "heading": "kafa vuruşu", "bicycle kicks": "röveşatalar", "loyal": "sadık", "refused": "reddetti", "offers": "teklifler", "richer": "daha zengin", "zero": "sıfır", "sportsmanship": "sportmenlik", "warm": "sıcak" },
    questions: [ {q:"Was Uwe Seeler from Germany?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he very tall?", a_en:"No", a_tr:"Hayır"}, {q:"Was he fantastic at heading the ball?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play his entire club career for Hamburger SV?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play in four World Cups?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win zero World Cups?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he a massive hero in Germany?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["49_DenisLaw.mp3"] = [{
    text: "Denis Law is a legendary football player from Scotland. He was born in 1940. He played as a striker and was famous for his amazing agility and quick reflexes. Fans called him 'The King' at Old Trafford, the stadium of Manchester United. He played for Manchester United for 11 years and formed a famous attacking trio with Bobby Charlton and George Best. They helped the club win many trophies. In 1964, Law won the Ballon d'Or award. He is the only Scottish player to ever win this prize. He was a fierce competitor and always celebrated his goals with one arm raised in the air. He is also the joint top goalscorer in the history of the Scotland national team.",
    dict: { "agility": "çeviklik", "quick": "hızlı", "reflexes": "refleksler", "King": "Kral", "trio": "üçlü", "trophies": "kupalar", "only": "tek", "Scottish": "İskoç", "prize": "ödül", "fierce": "sert/ateşli", "raised": "kaldırılmış", "joint": "ortak" },
    questions: [ {q:"Is Denis Law from Scotland?", a_en:"Yes", a_tr:"Evet"}, {q:"Did fans call him 'The King'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he play for Manchester United for 11 years?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he win the Ballon d'Or in 1964?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he the only Scottish player to win this prize?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he celebrate goals with zero emotion?", a_en:"No", a_tr:"Hayır"}, {q:"Is he the joint top goalscorer for Scotland?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["50_JimmyGreaves.mp3"] = [{
    text: "Jimmy Greaves was a brilliant football player from England. He was born in 1940. He played as a striker and is one of the greatest goalscorers in English football history. He was very calm in front of the goal and could finish easily with both feet. Greaves played for Chelsea, Tottenham Hotspur, and West Ham United. He was the top scorer in the English First Division six times! He scored 357 goals in the top English league, which is a record that stood for many decades. He was part of the England squad that won the 1966 World Cup, although he got injured during the tournament. After he retired, he became a very popular football presenter on television. He passed away in 2021.",
    dict: { "brilliant": "harika", "history": "tarih", "calm": "sakin", "front": "ön", "feet": "ayaklar", "top scorer": "gol kralı", "six times": "altı kez", "league": "lig", "decades": "on yıllar/onlarca yıl", "squad": "kadro", "injured": "sakatlandı", "presenter": "sunucu" },
    questions: [ {q:"Was Jimmy Greaves a brilliant striker?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he finish easily with both feet?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the top scorer six times?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he score exactly zero goals in the league?", a_en:"No", a_tr:"Hayır"}, {q:"Was he part of the 1966 World Cup winning squad?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become a TV presenter later?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die in 2021?", a_en:"Yes", a_tr:"Evet"} ]
}];
